name: Github-Actions

on: [push, pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - env:
          DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
      name: Push
      run: |
        docker build -f Dockerfile . -t uditkarode/android-sdk-arch:latest
        echo "$DOCKER_PASS" | docker login -u "uditkarode" --password-stdin
        docker push uditkarode/android-sdk-arch:latest
